config/routes.rb
Rails.application.routes.draw do
  root 'pic#index'
  get 'pic/index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pic_controller.rb
class PicController < ApplicationController
  def index
  	if params[:search].present?
  		@pic = Animatedgifme.random(params[:search])
  	else
  		@pic = Animatedgifme.random("lol")
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pic_helper.rb
module PicHelper
end

app/views/layouts/_search.html.erb
<div class="col-md-12">
	<%= form_tag pic_index_path, :method => 'get' do %>
  		<%= text_field_tag :search, params[:search], :placeholder => 'Enter your favorite tag to search', :class => 'form-control' %>
	<% end %>
</div><!-- /input-group -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GifApp</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">


</head>
<body>
<%= yield %>

</body>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</html>

app/views/pic/index.html.erb
<div class="bs-example" data-example-id="navbar-form">
	<nav class="navbar navbar-default navbar-static-top"> 
		<div class="container-fluid"> 
			<div class="navbar-header"> 
				<%= link_to "Gif APP", root_url, class: 'navbar-brand' %>
			</div> 

				<ul class="nav navbar-nav navbar-left">
					<%= form_tag pic_index_path, :method => 'get', class:'navbar-form navbar-left', role: 'search' do %>
				  		<%= text_field_tag :search, params[:search], :placeholder => 'Enter your favorite tag to search', :class => 'form-control', :style => "width:300px;" %>
				  		<%= submit_tag "Search", class:' btn btn-success' %>
					<% end %> 
					<button onclick="myFunction()" class="btn btn-info navbar-btn">Reload Page</button>
				</ul>

		</div> 
	</nav> 
</div>

<div class="tv">

	
</div>


<script type="text/javascript">
function myFunction() {
    location.reload();
}
</script>

<style type="text/css">
.tv {
	background-image: url('<%= @pic %>');
	background-size: 100% 100%;
	margin-top: 
	background-repeat: no-repeat;
	margin-top: 30px;
	margin-left: auto;
	margin-right: auto;
	-webkit-border-radius: 5px;
	-moz-border-radius: 5px;
	border-radius: 5px;
	width: 100%;
	height: 600px;
}


</style>